volumes:
  jornadas-storage:
    driver: local

networks:
  cae-services:
    external: true

services:
  front:
    image: registrygitlab.ssaver.gob.mx/jornadas-medicas/jornadas_front/app:latest-test
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - cae-services
    deploy:
      replicas: 1