volumes:
  jornadas-storage:
    driver: local

networks:
  cae-services:
    external: true


services:
  front:
    image: jornadas2026/jornadasmedicas:front
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - cae-services
    deploy:
      replicas: 1